// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastmm
Eigen::MatrixXd fastmm(const Eigen::MatrixXd& A, const Eigen::MatrixXd& B);
RcppExport SEXP _burgle_fastmm(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmm(A, B));
    return rcpp_result_gen;
END_RCPP
}
// simulate_responses
List simulate_responses(NumericMatrix preds, int sims, bool se, double rss);
RcppExport SEXP _burgle_simulate_responses(SEXP predsSEXP, SEXP simsSEXP, SEXP seSEXP, SEXP rssSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type preds(predsSEXP);
    Rcpp::traits::input_parameter< int >::type sims(simsSEXP);
    Rcpp::traits::input_parameter< bool >::type se(seSEXP);
    Rcpp::traits::input_parameter< double >::type rss(rssSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_responses(preds, sims, se, rss));
    return rcpp_result_gen;
END_RCPP
}
// simulate_responses_limits
List simulate_responses_limits(NumericMatrix preds, int sims, bool se, double rss, NumericVector limits);
RcppExport SEXP _burgle_simulate_responses_limits(SEXP predsSEXP, SEXP simsSEXP, SEXP seSEXP, SEXP rssSEXP, SEXP limitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type preds(predsSEXP);
    Rcpp::traits::input_parameter< int >::type sims(simsSEXP);
    Rcpp::traits::input_parameter< bool >::type se(seSEXP);
    Rcpp::traits::input_parameter< double >::type rss(rssSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type limits(limitsSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_responses_limits(preds, sims, se, rss, limits));
    return rcpp_result_gen;
END_RCPP
}
// simulate_responses_binom
List simulate_responses_binom(NumericMatrix preds, int sims);
RcppExport SEXP _burgle_simulate_responses_binom(SEXP predsSEXP, SEXP simsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type preds(predsSEXP);
    Rcpp::traits::input_parameter< int >::type sims(simsSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_responses_binom(preds, sims));
    return rcpp_result_gen;
END_RCPP
}
// sample_time2
int sample_time2(NumericVector Haz);
RcppExport SEXP _burgle_sample_time2(SEXP HazSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Haz(HazSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_time2(Haz));
    return rcpp_result_gen;
END_RCPP
}
// get_time_event2
DataFrame get_time_event2(List chst);
RcppExport SEXP _burgle_get_time_event2(SEXP chstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type chst(chstSEXP);
    rcpp_result_gen = Rcpp::wrap(get_time_event2(chst));
    return rcpp_result_gen;
END_RCPP
}
// sample_time_event
DataFrame sample_time_event(List chst);
RcppExport SEXP _burgle_sample_time_event(SEXP chstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type chst(chstSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_time_event(chst));
    return rcpp_result_gen;
END_RCPP
}
// combine_hazards
List combine_hazards(List chst);
RcppExport SEXP _burgle_combine_hazards(SEXP chstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type chst(chstSEXP);
    rcpp_result_gen = Rcpp::wrap(combine_hazards(chst));
    return rcpp_result_gen;
END_RCPP
}
// update_hazards
List update_hazards(NumericMatrix lps, List chs);
RcppExport SEXP _burgle_update_hazards(SEXP lpsSEXP, SEXP chsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type lps(lpsSEXP);
    Rcpp::traits::input_parameter< List >::type chs(chsSEXP);
    rcpp_result_gen = Rcpp::wrap(update_hazards(lps, chs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_burgle_fastmm", (DL_FUNC) &_burgle_fastmm, 2},
    {"_burgle_simulate_responses", (DL_FUNC) &_burgle_simulate_responses, 4},
    {"_burgle_simulate_responses_limits", (DL_FUNC) &_burgle_simulate_responses_limits, 5},
    {"_burgle_simulate_responses_binom", (DL_FUNC) &_burgle_simulate_responses_binom, 2},
    {"_burgle_sample_time2", (DL_FUNC) &_burgle_sample_time2, 1},
    {"_burgle_get_time_event2", (DL_FUNC) &_burgle_get_time_event2, 1},
    {"_burgle_sample_time_event", (DL_FUNC) &_burgle_sample_time_event, 1},
    {"_burgle_combine_hazards", (DL_FUNC) &_burgle_combine_hazards, 1},
    {"_burgle_update_hazards", (DL_FUNC) &_burgle_update_hazards, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_burgle(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
