# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastmm <- function(A, B) {
    .Call(`_burgle_fastmm`, A, B)
}

simulate_responses <- function(preds, sims, se, rss) {
    .Call(`_burgle_simulate_responses`, preds, sims, se, rss)
}

simulate_responses_limits <- function(preds, sims, se, rss, limits) {
    .Call(`_burgle_simulate_responses_limits`, preds, sims, se, rss, limits)
}

simulate_responses_binom <- function(preds, sims) {
    .Call(`_burgle_simulate_responses_binom`, preds, sims)
}

sample_time2 <- function(Haz) {
    .Call(`_burgle_sample_time2`, Haz)
}

get_time_event2 <- function(chst) {
    .Call(`_burgle_get_time_event2`, chst)
}

sample_time_event <- function(chst) {
    .Call(`_burgle_sample_time_event`, chst)
}

combine_hazards <- function(chst) {
    .Call(`_burgle_combine_hazards`, chst)
}

update_hazards <- function(lps, chs) {
    .Call(`_burgle_update_hazards`, lps, chs)
}

